#!/usr/bin/env sh
#  . "$(dirname -- "$0")/_/husky.sh"
# IMPORTANT: If you update this file run `pnpm install` and check the logs for `husky - Git hooks installed` to see if installation was successful.

# Run the build command
echo "Starting build process..."

npm run build

# Check if the build was successful
if [ $? -ne 0 ]; then
  echo "🚨 Build failed! Please fix the errors before pushing your code."
  exit 1  # Exit with failure to prevent push
else
  echo "✅ Build completed successfully! Proceeding with the push."
fi
